language: cpp

compiler:
    - clang
    - gcc

before_install:
    - curl -O http://www.cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz
    - tar -xf cmake-3.1.3-Linux-x86_64.tar.gz
    - export PATH=$PWD/cmake-3.1.3-Linux-x86_64/bin:$PATH

script:
    - ./tools/test_all.py
